name: built_redux_todos
version: 0.0.0
description:
   todo example
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_dev_tools
dependencies:
  built_redux: ^7.0.0
  built_collection: "^2.0.0"
  built_value: "^4.0.0"

dev_dependencies:
  build_runner: ^0.4.0
  built_value_generator: ^4.0.0
  coverage: "^0.7.3"
  dart_dev: "^1.0.0"
  dart_style: ">=0.2.0 <0.3.0"
  dartdoc: ">=0.8.0 <=0.10.0"
  test: "^0.12.6+2"

transformers:
  - $dart2js

environment:
  sdk: ">=1.23.0 <2.0.0"

web:
  compiler:
    debug: dartdevc